import { Minus, Plus, Trash2 } from "lucide-react";
import { formatMoney, formatPercent } from "@/lib/money";
import type { EvaluatedLine } from "@/modules/pricing/types";

type Variant = { id: number; attributeName: string; attributeValue: string; extraPricePaise: number };
export type BuilderLine = { productId: number; variantId: number | null; qty: number; lineDiscountBps: number };
export function LineRow({ line, calculated, name, listPricePaise, variants, editable, onChange, onRemove }: { line: BuilderLine; calculated: EvaluatedLine; name: string; listPricePaise: number; variants: Variant[]; editable: boolean; onChange: (line: BuilderLine) => void; onRemove: () => void }) {
  return <div className={`quote-line ${calculated.excessBps > 0 ? "over" : ""}`}><div className="line-product"><strong>{name}</strong>{variants.length > 0 && <select disabled={!editable} value={line.variantId ?? ""} onChange={(e) => onChange({ ...line, variantId: Number(e.target.value) })}>{variants.map((variant) => <option value={variant.id} key={variant.id}>{variant.attributeName}: {variant.attributeValue}</option>)}</select>}<small><s>{formatMoney(listPricePaise + (variants.find((v) => v.id === line.variantId)?.extraPricePaise ?? 0))}</s> tier price {formatMoney(calculated.unitPricePaise)}</small></div><div className="qty-control"><button disabled={!editable || line.qty <= 1} onClick={() => onChange({ ...line, qty: line.qty - 1 })}><Minus size={14}/></button><input aria-label={`${name} quantity`} disabled={!editable} type="number" min="1" value={line.qty} onChange={(e) => onChange({ ...line, qty: Math.max(1, Number(e.target.value)) })}/><button disabled={!editable} onClick={() => onChange({ ...line, qty: line.qty + 1 })}><Plus size={14}/></button></div><label className="discount-input"><span>Line discount</span><div><input disabled={!editable} type="number" min="0" max="100" step="0.1" value={line.lineDiscountBps / 100} onChange={(e) => onChange({ ...line, lineDiscountBps: Math.round(Number(e.target.value) * 100) })}/><b>%</b></div></label><div className="line-policy"><span>Allowed {formatPercent(calculated.allowedDiscountBps)}</span>{calculated.excessBps > 0 ? <strong>+{calculated.excessBps / 100} pts over</strong> : <em>Within policy</em>}</div><div className="line-net"><span>Net</span><strong>{formatMoney(calculated.netPaise)}</strong></div>{editable && <button className="icon-button" aria-label={`Remove ${name}`} onClick={onRemove}><Trash2 size={16}/></button>}</div>;
}
