"use client";
import { useMemo, useState } from "react";
import { cancelSubscription, modifySubscription } from "@/modules/billing/actions";
import { prorate, subscriptionPeriod } from "@/modules/billing/prorate";
import { formatMoney } from "@/lib/money";

export function SubscriptionChangeForm({ subscription, orderCode }: { subscription: { id: number; qty: number; unitPricePaise: number; startsAt: string; status: string; plan: { interval: "MONTHLY" | "QUARTERLY" | "YEARLY"; prorateChanges: boolean; creditOnCancel: boolean } }; orderCode: string }) {
  const today = new Date().toISOString().slice(0, 10); const [newQty, setNewQty] = useState(subscription.qty + 1); const [effectiveDate, setEffectiveDate] = useState(today);
  const preview = useMemo(() => { const period = subscriptionPeriod(subscription.startsAt, effectiveDate, subscription.plan.interval); return prorate({ unitAmountPaise: subscription.unitPricePaise, qtyDelta: newQty - subscription.qty, effectiveDate, periodStart: period.periodStart, periodEnd: period.periodEnd, prorateChanges: subscription.plan.prorateChanges }); }, [effectiveDate, newQty, subscription]);
  const cancelPreview = useMemo(() => { const period = subscriptionPeriod(subscription.startsAt, effectiveDate, subscription.plan.interval); return prorate({ unitAmountPaise: subscription.unitPricePaise, qtyDelta: -subscription.qty, effectiveDate, periodStart: period.periodStart, periodEnd: period.periodEnd, prorateChanges: subscription.plan.creditOnCancel }); }, [effectiveDate, subscription]);
  if (subscription.status !== "ACTIVE") return <p className="muted">This subscription is {subscription.status.toLowerCase()}.</p>;
  return <div className="subscription-actions"><details><summary>Modify subscription</summary><form action={modifySubscription}><input type="hidden" name="subscriptionId" value={subscription.id}/><input type="hidden" name="orderCode" value={orderCode}/><div className="form-row"><label>New quantity<input name="newQty" type="number" min="0" value={newQty} onChange={(event) => setNewQty(Number(event.target.value))}/></label><label>Effective date<input name="effectiveDate" type="date" value={effectiveDate} onChange={(event) => setEffectiveDate(event.target.value)}/></label></div><div className="math-preview"><b>{formatMoney(preview.amountPaise)}</b><span>{preview.reason}</span></div><button className="button primary small">Confirm modification</button></form></details><details><summary>Cancel subscription</summary><form action={cancelSubscription}><input type="hidden" name="subscriptionId" value={subscription.id}/><input type="hidden" name="orderCode" value={orderCode}/><input type="hidden" name="effectiveDate" value={effectiveDate}/><div className="math-preview"><b>{formatMoney(cancelPreview.amountPaise)}</b><span>{cancelPreview.reason}</span></div><button className="button danger small">Confirm cancellation</button></form></details></div>;
}
