"use client";
import { useMemo, useState } from "react";
import { cancelSubscription, modifySubscription, pauseSubscription, resumeSubscription } from "@/modules/billing/actions";
import { prorate, subscriptionPeriod } from "@/modules/billing/prorate";
import { grossPaise } from "@/modules/billing/invoice-balance";
import { formatMoney } from "@/lib/money";

export function SubscriptionChangeForm({ subscription, orderCode }: { subscription: { id: number; qty: number; unitPricePaise: number; startsAt: string; status: string; taxBps: number; plan: { interval: "MONTHLY" | "QUARTERLY" | "YEARLY"; prorateChanges: boolean; creditOnCancel: boolean } }; orderCode: string }) {
  const today = new Date().toISOString().slice(0, 10); const [newQty, setNewQty] = useState(subscription.qty + 1);
  const preview = useMemo(() => { const period = subscriptionPeriod(subscription.startsAt, today, subscription.plan.interval); return prorate({ unitAmountPaise: subscription.unitPricePaise, qtyDelta: newQty - subscription.qty, effectiveDate: today, periodStart: period.periodStart, periodEnd: period.periodEnd, prorateChanges: subscription.plan.prorateChanges }); }, [newQty, subscription, today]);
  const cancelPreview = useMemo(() => { const period = subscriptionPeriod(subscription.startsAt, today, subscription.plan.interval); return prorate({ unitAmountPaise: subscription.unitPricePaise, qtyDelta: -subscription.qty, effectiveDate: today, periodStart: period.periodStart, periodEnd: period.periodEnd, prorateChanges: subscription.plan.creditOnCancel }); }, [subscription, today]);
  if (subscription.status === "PAUSED") {
    return <form action={resumeSubscription} className="subscription-actions"><input type="hidden" name="subscriptionId" value={subscription.id}/><input type="hidden" name="orderCode" value={orderCode}/><p className="muted">Billing is paused. Upcoming scheduled periods were skipped. Resume to put the next cycles back on the schedule.</p><button className="button primary small">Resume subscription</button></form>;
  }
  if (subscription.status !== "ACTIVE") return <p className="muted">This subscription is {subscription.status.toLowerCase()}.</p>;
  return <div className="subscription-actions"><details><summary>Modify subscription</summary><form action={modifySubscription}><input type="hidden" name="subscriptionId" value={subscription.id}/><input type="hidden" name="orderCode" value={orderCode}/><input type="hidden" name="effectiveDate" value={today}/><div className="form-row"><label>New quantity<input name="newQty" type="number" min="0" value={newQty} onChange={(event) => setNewQty(Number(event.target.value))}/></label></div><p className="muted">Takes effect today. Credits include tax so unpaid invoices can close.</p><div className="math-preview"><b>{formatMoney(grossPaise(preview.amountPaise, subscription.taxBps))}</b><span>{preview.reason}</span></div><button className="button primary small">Confirm modification</button></form></details><details><summary>Pause subscription</summary><form action={pauseSubscription}><input type="hidden" name="subscriptionId" value={subscription.id}/><input type="hidden" name="orderCode" value={orderCode}/><p className="muted">Stops the billing schedule. Future scheduled periods are skipped and will not be invoiced on resume.</p><button className="button secondary small">Pause billing</button></form></details><details><summary>Cancel subscription</summary><form action={cancelSubscription}><input type="hidden" name="subscriptionId" value={subscription.id}/><input type="hidden" name="orderCode" value={orderCode}/><input type="hidden" name="effectiveDate" value={today}/><p className="muted">Takes effect today. Unused-time credit includes tax.</p><div className="math-preview"><b>{formatMoney(grossPaise(cancelPreview.amountPaise, subscription.taxBps))}</b><span>{cancelPreview.reason}</span></div><button className="button danger small">Confirm cancellation</button></form></details></div>;
}
