import { formatMoney } from "@/lib/money";

type InvoiceData = Awaited<ReturnType<typeof import("@/modules/billing/queries").getInvoice>>;

export function InvoicePrint({ invoice }: { invoice: NonNullable<InvoiceData> }) {
  const credits = invoice.creditNotes.reduce((sum, note) => sum + note.amountPaise, 0);
  const balance = Math.max(0, invoice.totalPaise - invoice.paidPaise - credits);
  return <article className="print-document invoice-print"><header><div><span className="eyebrow">AccordFlow</span><h1>Invoice {invoice.code}</h1><p>Quote {invoice.order.quote.code} · Order {invoice.order.code}</p></div><div><strong>Issued {invoice.issuedAt.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</strong><small>Due {invoice.dueAt.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</small></div></header><section className="print-addresses"><div><span>From</span><strong>AccordFlow</strong><p>Deal governance and sales operations</p></div><div><span>Bill to</span><strong>{invoice.order.quote.customer.name}</strong><p>{invoice.order.quote.customer.email}</p></div></section><table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Tax</th><th>Total</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id}><td>{line.description}</td><td>{line.qty}</td><td>{formatMoney(line.unitPaise)}</td><td>{formatMoney(line.taxPaise)}</td><td>{formatMoney(line.totalPaise)}</td></tr>)}</tbody></table><div className="print-totals"><span>Total <b>{formatMoney(invoice.totalPaise)}</b></span><span>Paid <b>{formatMoney(invoice.paidPaise)}</b></span><span>Credits <b>{formatMoney(credits)}</b></span><span className="grand">Balance <b>{formatMoney(balance)}</b></span></div>{invoice.payments.length > 0 && <section><h2>Payments</h2>{invoice.payments.map((payment) => <p key={payment.id}>{payment.reference} · {payment.method} · {formatMoney(payment.amountPaise)} · {payment.receivedAt.toLocaleDateString("en-IN")}</p>)}</section>}</article>;
}
